# Generated by Django 4.1.7 on 2023-02-24 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='Images/Product/')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('Mobiles', (('Mobile_Phones', 'Mobile Phones'), ('Tablets', 'Tablets'), ('Accessories', 'Accessories'), ('otherwise', 'otherwise'))), ('Electronics&Appliances', (('Computers&Accessories', 'Computers & Accessories'), ('Tv-Video-Audio', 'Tv - Video - Audio'), ('Games&Entertainment', 'Games & Entertainment'), ('Cameras&Accessories', 'Cameras & Accessories'), ('Fridge_AC_Washing_Machine', 'Fridge - AC - Washing Machine'), ('Kitchen&OtherAppliances', 'Kitchen & Other Appliances'))), ('Cars', (('Spare_Parts', 'Spare Parts'), ('Other_Vehicles', 'Other Vehicles'), ('Spare_Parts', 'Spare Parts'), ('Cameras&Accessories', 'Cameras & Accessories'), ('Fridge_AC_Washing_Machine', 'Fridge - AC - Washing Machine'), ('Kitchen&OtherAppliances', 'Kitchen & Other Appliances'))), ('Bikes', (('Bicycles', 'Bicycles'), ('Scooters', 'Scooters'), ('Spare_Parts', 'Spare Parts'), ('Motorcycles', 'Motorcycles')))], max_length=30)),
                ('title', models.CharField(max_length=20)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, null=True)),
                ('states', models.IntegerField(blank=True, default=0, null=True)),
                ('company', models.CharField(max_length=20)),
                ('state', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.buyer')),
            ],
        ),
    ]
