# Generated by Django 4.1.7 on 2023-02-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_advertisement_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_trend',
            field=models.BooleanField(default=False),
        ),
    ]
