# Generated by Django 4.1.7 on 2023-03-06 01:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_categories_options_alter_categories_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='Id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='images',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
