# Generated by Django 4.1.7 on 2023-02-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_advertisement_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='id',
            new_name='Id',
        ),
    ]
